---
title: "OCt24"
author: "Kristen"
date: "2024-10-24"
output: html_document
---

```{r}
library(metagear)
library(readr)
interpapers <- read_csv("interpapers.csv")
library(tidyr)
library(dplyr)

```

```{r}
References_Screening_Ready <- effort_initialize(interpapers)
theTeam<- c("Kristen1", "Kristen2", "Kristen3")

#Randomly delegate screening
References_unscreened <- effort_distribute(References_Screening_Ready, reviewers=theTeam, save_split=TRUE)


metagear::abstract_screener(file=file.choose("interpapers.csv"),
                            aReviewer = "Kristen3" ,
                            reviewerColumnName = "REVIEWERS",
                            unscreenedColumnName = "INCLUDE",
                            unscreenedValue = "not vetted",
                            abstractColumnName = "Abstract",
                            titleColumnName =  "Article.Title" ,
                            browserSearch = "https://www.google.com/search?q=",
                            fontSize = 13,
                            windowWidth = 70,
                            windowHeight = 16,
                            theButtons = c("YES","maybe","NO"),
                            keyBindingToButtons = c("y","m","n"),
                            buttonSize = 10,
                            highlightColor = "powderblue",
                            highlightKeywords = c("interdisci*", "ecolog*"))


```

```{r}
df_Kristen<-rbind(effort_Kristen1, effort_Kristen2, effort_Kristen3)
write.csv(df_Kristen, "df_Kristen.csv")
```

```{r}
combined_screen <- read_csv("combined_screen.csv")
```
```{r}
#was maybe now no 17, 43, 51, 81, 189, 410, 446,  104, 134, 776, 256,258, 7,  287, 293, 296, 301, 304, 310, 320, 322, 323, 328, 333, 350, 351, 353, 371, 375, 380, 400, 410, 437, 444, 446, 449, 450, 500, 519, 554, 564, 565, 569, 600, 865, 905
# was maybe now yes 80, 85, 86,  351, 156, 191, 5, 8, 292
# no but 474, 208, 289, 474, 479, 499, 613, 776

combined_file_edited <- combined_screen %>% 
  mutate(INCLUDE = case_when(
    STUDY_ID %in% c(22, 67, 84, 385, 103, 
                    17, 43, 51, 81, 189, 410, 446, 104, 134, 776, 256, 258, 7, 
                    287, 293, 296, 301, 304, 310, 320, 322, 323, 328, 333, 350, 
                    351, 353, 371, 375, 380, 400, 410, 437, 444, 446, 449, 450, 
                    500, 519, 554, 564, 565, 569, 600, 865, 905, 474, 208, 289, 
                    474, 479, 499, 613, 776) ~ "NO",
    STUDY_ID %in% c(80, 85, 86, 351, 156, 191, 5, 8, 292) ~ "YES",
    INCLUDE == "MAYBE" ~ "NO",  # Remaining "MAYBE" values change to "NO"
    TRUE ~ INCLUDE
  ))

```

